### PR TITLE
Make enums enumerable

### PR DESCRIPTION
**Pull request by uvlad7**
Slightly refactor `Enum:define_methods` and include `Enumerable`

### CODE REVIEW

**Comment by uvlad7** [comment]
I'm not sure if `rb_block_given_p()` should be wrapped into `detail::protect`, pls review.

**Comment by jasonroelofs** [comment]
Can you write a few tests to show that this works?

File: rice/Enum.ipp [hunk 1]
```diff
@@ -84,17 +84,24 @@ namespace Rice
...
+    klass.define_singleton_function("each", [klass]()
         {
-          for (auto& pair : valuesToNames_)
-          {
-            Enum_T enumValue = pair.first;
-            VALUE value = detail::To_Ruby<Enum_T>().convert(enumValue);
-            detail::protect(rb_yield, value);
-          }
+//        Get rid of LocalJumpErrors
+            if (detail::protect(rb_block_given_p))
```
Comment (jasonroelofs) [inline rice/Enum.ipp:91]: This probably doesn't need to be protected as there's no required object conversion going on, but you're also not calling `rb_block_given_p` here (missing the parens) so I'm not sure this even compiles?.

Comment (uvlad7) [reply rice/Enum.ipp:91]: Well, it compiles. Isn't it how `detail::protect` is supposed to work? I mean, it accepts a function pointer and calls it.
But now I see it's not required, because no ruby exception can be raised in `rb_block_given_p`.

**Comment by uvlad7** [comment]
> Can you write a few tests to show that this works?

Yep

File: rice/Enum.ipp (hunk 1 above)
Comment (jasonroelofs) [reply rice/Enum.ipp]: Sorry, you're right, been a while since I've looked at this code.

**Comment by uvlad7** [comment]
Well, I don't understand what's happening. I've removed all tests but `test_Enum.cpp` before to test faster. Now I restored them and tried to run them on ruby 3.0.0 and 3.2.0. No surprises, all tests were successful, and I really don't understand how that error `undefined method `class' for #<Enumerator: Color:each>` can happen. Everything is a class and has a `class` method.

```
vladimir@np940x5n:~/rice/test$ make clean && ruby extconf.rb && make && ./unittest
...
335 test(s), 974 assertion(s), 0 error(s), 0 failure(s)
vladimir@np940x5n:~/rice/test$ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

vladimir@np940x5n:~/rice/test$ make clean && ruby extconf.rb && make && ./unittest
...
335 test(s), 974 assertion(s), 0 error(s), 0 failure(s)
vladimir@np940x5n:~/rice/test$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
```

I also don't understand how my changes could trigger that error in [tests (windows-latest, 3.2)](https://github.com/jasonroelofs/rice/actions/runs/4152206656/jobs/7183650484#logs):
`Data_Object:ruby_custom_free: Assertion failed: true != test_destructor_called (1 != 0) at test_Data_Object.cpp:213`

**Comment by jasonroelofs** [comment]
Right, the Windows test failure is not related to your changes, it's a known issue I need to fix. 

As for the relevant error, that is strange. Why did you switch from `define_singleton_method` to `define_singleton_function`?

**Comment by uvlad7** [comment]
Well, I've found it confusing to have a local variable `klass` of type `Data_Type` and an argument `klass` of type `VALUE`? Is it really necessary to unwrap `VALUE` every time the method is called? And it seems that `klass.call("to_enum")` calls were successful

**Comment by uvlad7** [comment]
oops, I made a capture by copy, maybe that's the problem

**Comment by uvlad7** [comment]
still don't understand why these lambdas worked well without `Arg().isValue()`

**Comment by uvlad7** [comment]
I've reproduced the error with `bundle exec rake test`. Sorry, my bad, I forgot about `bundler`

**Comment by uvlad7** [comment]
Well, I've cleaned test files incorrectly, that's why I couldn't reproduce the error - the Makefile was still using Ruby 2.7.0.
But look, even this `Class(detail::protect(rb_eval_string, "1.class"))` raises an exception:
```
Enum:each_without_block: undefined method `class' for 1:Integer
```
Something is definitely wrong with embedding ruby into the unittest executable.

**Comment by jasonroelofs** [comment]
Yeah, I don't understand why even `1.class` doesn't exist. Curious if this is a relatively new change to Ruby?

**Comment by uvlad7** [comment]
I checked how a regular Ruby process [starts](https://github.com/ruby/ruby/blob/master/main.c#L34) and didn't found any differences from the unittest. But obviously there is one.

What if I rewrite all the tests to be compiled into shared libraries without Ruby embedding and run them with a regular `require`? I already tried to compile the unittest into shared library and run `main` using `ffi`, because hacks in `extconf.rb` don't work with ruby 2.3.8 and I wanted to fix it somehow. Unfortunately I've lost that piece of code, but it was just a POC. All tests were passed, but my `irb` session became very unresponsive, may be because a second interpreter was initialized. Btw, I also tried to fix the Makefile manually and build the unittest executable for ruby 2.3.8, and all the test were passed (except one, `Integer` vs `Fixnum`, not a real issue). So, I think it's possible to remove Ruby embedding from the tests and build them into shared objects. To run them, there are two options: run `main` using `fiddle` or `fii` in a ruby subprocess to avoid the tests interfering with each other. The second one is to replace `main` function with `Init_testname` and start them with a regular `load` or `require`, still in a subprocess, of course.

**Comment by uvlad7** [comment]
More experiments

<pre><font color="#4E9A06"><b>vladimir@np940x5n</b></font>:<font color="#3465A4"><b>~/rice/test</b></font>$ irb
3.0.0 :001 &gt; require &apos;ffi&apos;
module Unittest
 extend FFI::Library
end
Unittest.ffi_lib &apos;./unittest.so&apos;
Unittest.attach_function :main, [:int, :pointer], :int

argv = FFI::MemoryPointer.new(:pointer, 1)
argv[0].put_pointer(0, FFI::MemoryPointer.from_string(&apos;unittest&apos;))
 =&gt; #&lt;FFI::Pointer address=0x00005619f3e1d2b0 size=8&gt; 
3.0.0 :010 &gt; Unittest.main 1, argv
Enum:copy_construct .
Enum:assignment .
Enum:each .
Enum:each_without_block Integer
#&lt;Class:#&lt;Enumerator:0x00005619f3e54a80&gt;&gt;
.
Enum:enumerable_methods .
Enum:each_seasons .
Enum:to_s .
Enum:to_i .
Enum:inspect .
Enum:compare .
Enum:eql .
Enum:compare_equal .
Enum:compare_less .
Enum:compare_more .
Enum:different_objects_eql .
Enum:hash .
Enum:from_int .
Enum:from_int_invalid .
Enum:nested_enums .
Enum:using_enums .
Enum:default_argument .
Enum:not_defined .

22 test(s), 53 assertion(s), 0 error(s), 0 failure(s)
 =&gt; <font color="#3465A4"><b>0</b></font> 
3.0.0 :012 &gt; 

<font color="#4E9A06"><b>vladimir@np940x5n</b></font>:<font color="#3465A4"><b>~/rice/test</b></font>$ git diff -- extconf.rb
<b>diff --git a/test/extconf.rb b/test/extconf.rb</b>
<b>index a55d18d..2f2e20c 100644</b>
<b>--- a/test/extconf.rb</b>
<b>+++ b/test/extconf.rb</b>
<font color="#06989A">@@ -7,17 +7,4 @@</font> require &apos;rbconfig&apos;
 target_exe = &quot;unittest#{RbConfig::CONFIG[&apos;EXEEXT&apos;]}&quot;
 $cleanfiles &lt;&lt; target_exe
 
<font color="#CC0000">-create_makefile(target_exe) do |conf|</font>
<font color="#CC0000">-  conf &lt;&lt; &quot;\n&quot;</font>
<font color="#CC0000">-  conf &lt;&lt; &quot;#{target_exe}: $(OBJS)&quot;</font>
<font color="#CC0000">-  conf &lt;&lt; &quot;\t$(ECHO) linking executable unittest&quot;</font>
<font color="#CC0000">-  conf &lt;&lt; &quot;\t-$(Q)$(RM) $(@)&quot;</font>
<font color="#CC0000">-</font>
<font color="#CC0000">-  if IS_MSWIN</font>
<font color="#CC0000">-    conf &lt;&lt; &quot;\t$(Q) $(CXX) -Fe$(@) $(OBJS) $(LIBS) $(LOCAL_LIBS) -link $(ldflags) $(LIBPATH)&quot;</font>
<font color="#CC0000">-  else</font>
<font color="#CC0000">-    conf &lt;&lt; &quot;\t$(Q) $(CXX) -o $@ $(OBJS) $(LIBPATH) $(LOCAL_LIBS) $(LIBS)&quot;</font>
<font color="#CC0000">-  end</font>
<font color="#CC0000">-</font>
<font color="#CC0000">-  conf &lt;&lt; &quot;\n&quot;</font>
<font color="#CC0000">-end</font>
<font color="#4E9A06">+create_makefile(target_exe)</font>
\ No newline at end of file
<font color="#4E9A06"><b>vladimir@np940x5n</b></font>:<font color="#3465A4"><b>~/rice/test</b></font>$ git diff -- embed_ruby.cpp
<b>diff --git a/test/embed_ruby.cpp b/test/embed_ruby.cpp</b>
<b>index 719de7c..aa0c05b 100644</b>
<b>--- a/test/embed_ruby.cpp</b>
<b>+++ b/test/embed_ruby.cpp</b>
<font color="#06989A">@@ -7,14 +7,6 @@</font> void embed_ruby()
 
   if (!initialized__)
   {
<font color="#CC0000">-    int argc = 0;</font>
<font color="#CC0000">-    char* argv = nullptr;</font>
<font color="#CC0000">-    char** pArgv = &amp;argv;</font>
<font color="#CC0000">-</font>
<font color="#CC0000">-    ruby_sysinit(&amp;argc, &amp;pArgv);</font>
<font color="#CC0000">-    ruby_init();</font>
<font color="#CC0000">-    ruby_init_loadpath();</font>
<font color="#CC0000">-</font>
     initialized__ = true;
 
     // Because Ruby 3 no longer initializes the GC module when embedding, calling GC.stress 
<font color="#4E9A06"><b>vladimir@np940x5n</b></font>:<font color="#3465A4"><b>~/rice/test</b></font>$ 
</pre>

**Comment by jasonroelofs** [comment]
FYI I disabled the test that's failing on Windows on master, feel free to rebase on that.

As for re-jiggering the test suite to be loadable libraries, the more I think about it the more it does make sense. It would test the library in a more correct way. There's nothing else about Rice that tries to embed Ruby in another process except for `unittest` (well there was a `VM` class for this but it was unused and got deleted) and we've had other weird failure cases related to the current setup. Feel free to play with some ideas yourself, I'll play with it as well.

**Comment by uvlad7** [comment]
Uh, I forgot about that every push triggers a workflow approval, sorry. It's not necessary, it was just kind of a 'save my progress' commit.

And while reading the tests I've found an interesting thing. All binaries are compiled with `rake test`, but only `unittest` is executed. There is also the issue with the `clean` task mentioned above which caused `unittest` to be built using the old `Makefile` and therefore the wrong version of ruby. And it also relies on the clean task, which calls `make clean` and thus relies on the `Makefile` being created before, so `rake test` fails if `rake build` wasn't called before. Just FYI - I'm gonna rewrite this. I believe using a temp directory to build and run the tests would be the best approach.

**Comment by cfis** [comment]
I understand that it seems a bit strange, but I think having the embedded ruby interpreter makes it easy to test. Wrapping everything into a shared library, to then wrap via FFI, would make debugging harder due in my view.

It also would preclude the ability to run one test at time (we don't have that now, but if we switched to Google Test we could).

**Comment by uvlad7** [comment]
@cfis what about making `require`-able shared library? This should work most similar to how it works in gems.

**Comment by cfis** [comment]
@uvlad7 - thanks for the idea and code on to_enum. 

See if this works for you:

https://github.com/jasonroelofs/rice/commit/c7f9be5fabdd9a5c43292491cbe2e7882e2198e1

Its similar to what you posted above. If this works (and tests pass), I will close this pull request.

**Comment by uvlad7** [comment]
@cfis yep, I mean creating a lib - shared object - for the tests. I hope it'll make easier to run tests in comparison to the FFI approach. It's possible to define a some class in that library, or just move all code from the `main` into `Init_libname`, so it'll be executed on `require 'libname'`. Unfortunately, I don't have enough time for that right now, but I'm still gonna try some day.

Sure, you can close the PR. But it seems you've forgot to add this `klass.singleton_class().include_module(rb_mEnumerable)`. And could you rename `klass` to `ruby_klass` [here](https://github.com/jasonroelofs/rice/blob/master/rice/Enum.ipp#L106), like you did in the `each`, to avoid confusion?

**Comment by cfis** [comment]
Notice in the samples directory, the code is packaged as shared libraries which are ruby extensions and then the test file is test.rb. 

I don't think you need ffi to package the tests into a library - instead make it a ruby extension too (so like you said with `Init_libname`. But I'm not sure what that really achieves?

Good points on the PR, will make those changes.

**Comment by cfis** [comment]
Update pushed. Will close this PR. Feel free to open a new one if you have any issues.
